# Generated by Django 4.0.4 on 2022-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('no_of_dests', models.IntegerField(default=1)),
                ('distance', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
